<script src="../Plugins/js/jquery-3.0.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="../Plugins/Moment/moment.min.js"></script>
<script src="../Plugins/js/umd/popper.min.js" type="text/javascript"></script>
<script src="../Plugins/js/bootstrap.min.js" type="text/javascript"></script>
<script src="../Plugins/BootstrapFileInput/js/fileinput.min.js" type="text/javascript"></script>
<script src="../Plugins/BootstrapFileInput/js/locales/es.js" type="text/javascript"></script>
<script type="text/javascript" src="../Plugins/Dominus/tempusdominus-bootstrap-4.min.js"></script>
<script src="../Plugins/fancybox/jquery.fancybox.js" type="text/javascript"></script>
<script src="../Plugins/sweetalert/sweetalert.min.js" type="text/javascript"></script>
<script src="../Plugins/jfvalidator/jquery.form-validator.min.js" type="text/javascript"></script>
<script src="../Plugins/jfvalidator/es.js" type="text/javascript"></script>
<script src="../Plugins/DataTables/js/jquery.dataTables.min.js" type="text/javascript"></script>
